[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold", "-Awarnings"]

[target.x86_64-pc-windows-msvc]
# linker = "lld-link.exe" # "clang"
rustflags = ["-C", "target-feature=+crt-static", "-Awarnings"]